apiVersion: v1
kind: Pod
metadata:
  name: app-volume
spec:
  containers:
  - name: app-volume
    image: gcr.io/kuar-demo/kuard-amd64:1
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 2
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10
    volumeMounts:
    - name: app-volume-storage
      mountPath: /data
  volumes:
  - name: app-volume-storage
    hostPath:
      path: /var/lib/app
