apiVersion: v1
kind: Pod
metadata:
  name: app-readinessprob
spec:
  containers:
  - name: app
    image: yamikhailov/demo_app:v2.0.0
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      periodSeconds: 2
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      periodSeconds: 10
