apiVersion: v1
kind: Pod
metadata:
  name: app-liveness
spec:
  containers:
  - name: app-container
    image: yamikhailov/demo_app:v2.0.0
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
