---
apiVersion: v1
kind: Pod
metadata:
  name: app-readinessprob
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /
          port: 8080
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
